backend/modules/wechat/controllers/ReplyDefaultController.php
<?php
namespace backend\modules\wechat\controllers;

use Yii;
use common\helpers\ArrayHelper;
use common\models\wechat\RuleKeyword;
use common\models\wechat\ReplyDefault;

/**
 * 默认回复控制器
 *
 * Class ReplyDefaultController
 * @package backend\modules\wechat\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class ReplyDefaultController extends WController
{
    /**
     * 首页
     *
     * @return mixed|string
     */
    public function actionIndex()
    {
        $model = $this->findModel();

        if ($model->load(Yii::$app->request->post()) && $model->save())
        {
            return $this->message('修改成功', $this->redirect(['index']));
        }

        // 关键字
        $keyword = RuleKeyword::getList();
        $keyword = ArrayHelper::map($keyword, 'content', 'content');
        $keyword = ArrayHelper::merge([' ' => '不触发关键字'], $keyword);

        return $this->render('index',[
            'model' => $model,
            'keyword' => $keyword
        ]);
    }

    /**
     * 返回模型
     *
     * @return array|ReplyDefault|null|yii\db\ActiveRecord
     */
    protected function findModel()
    {
        if (empty(($model = ReplyDefault::find()->one())))
        {
            return new ReplyDefault;
        }

        return $model;
    }
}

backend/modules/wechat/controllers/RuleController.php
<?php
namespace backend\modules\wechat\controllers;

use Yii;
use yii\data\Pagination;
use common\enums\StatusEnum;
use common\models\wechat\Rule;
use common\models\wechat\RuleKeyword;
use common\components\CurdTrait;
use backend\modules\wechat\models\RuleForm;

/**
 * Class RuleController
 * @package backend\modules\wechat\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class RuleController extends WController
{
    use CurdTrait;

    /**
     * @var string
     */
    public $modelClass = 'common\models\wechat\Rule';

    /**
     * @return string
     */
    public function actionIndex()
    {
        $request = Yii::$app->request;
        $module = $request->get('module', null);
        $keyword = $request->get('keyword', null);

        $data = Rule::find()
            ->where(['>=', 'status', StatusEnum::DISABLED])
            ->andWhere(['in', 'module', array_keys(Rule::$moduleExplain)])
            ->andFilterWhere(['module' => $module])
            ->andFilterWhere(['like', 'name', $keyword]);

        $pages = new Pagination(['totalCount' => $data->count(), 'pageSize' => $this->pageSize]);
        $models = $data->offset($pages->offset)
            ->orderBy('sort asc,created_at desc')
            ->with('ruleKeyword')
            ->limit($pages->limit)
            ->all();

        return $this->render($this->action->id, [
            'models' => $models,
            'pages' => $pages,
            'modules' => Rule::$moduleExplain,
            'module' => $module,
            'keyword' => $keyword,
        ]);
    }

    /**
     * 编辑更新
     *
     * @return mixed|string|\yii\web\Response
     * @throws \yii\db\Exception
     */
    public function actionEdit()
    {
        $request = Yii::$app->request;
        $id = $request->get('id');

        $model = $this->findModel($id);
        $model->module = $request->get('module');// 回复规则
        $defaultRuleKeywords = RuleKeyword::getRuleKeywordsType($model->ruleKeyword);
        $moduleModel = Rule::getModuleModel($id, $model->module);// 基础

        $postData = Yii::$app->request->post();
        if ($model->load($postData) && $moduleModel->load($postData))
        {
            $transaction = Yii::$app->db->beginTransaction();
            try
            {
                if (!$model->save())
                {
                   throw new \Exception($this->analyErr($model->getFirstErrors()));
                }

                 // 获取规则ID
                $moduleModel->rule_id = $model->id;
                // 全部关键字
                $ruleKey = isset($postData['ruleKey']) ? $postData['ruleKey'] : [];
                $ruleKey[RuleKeyword::TYPE_MATCH] = explode(',', $model->keyword);

                // 更新关键字
                RuleKeyword::updateKeywords($model, $ruleKey, $defaultRuleKeywords);

                // 插入模块数据
                if ($moduleModel->save())
                {
                    $transaction->commit();
                    return $this->redirect(['index', 'module' => $model->module]);
                }

                throw new \Exception('插入失败');
            }
            catch (\Exception $e)
            {
                $transaction->rollBack();
                return $this->message($e->getMessage(), $this->redirect(['index']), 'error');
            }
        }

        return $this->render($this->action->id, [
            'model' => $model,
            'moduleModel' => $moduleModel,
            'title' => Rule::$moduleExplain[$model->module],
            'ruleKeywords' => $defaultRuleKeywords,
        ]);
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return mixed
     */
    protected function findModel($id)
    {
        if (empty($id) || empty(($model = RuleForm::findOne($id))))
        {
            $model = new RuleForm();
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

backend/modules/wechat/controllers/SettingController.php
<?php
namespace backend\modules\wechat\controllers;

use Yii;
use common\models\wechat\Setting;
use backend\modules\wechat\models\HistoryForm;

/**
 * 微信参数设置
 *
 * Class SettingController
 * @package backend\modules\wechat\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class SettingController extends WController
{
    /**
     * 参数设置
     *
     * @return string|yii\web\Response
     */
    public function actionHistoryStat()
    {
        $model = new HistoryForm();
        $model->attributes = Setting::getData('history');
        if (Yii::$app->request->isPost && $model->validate())
        {
            if (Setting::setData('history', Yii::$app->request->post('HistoryForm')))
            {
                return $this->message('修改成功', $this->redirect(['history-stat']));
            }
        }

        return $this->render('history-stat',[
            'model' => $model,
        ]);
    }

    /**
     * 特殊消息回复
     *
     * @return string|yii\web\Response
     */
    public function actionSpecialMessage()
    {
        if (Yii::$app->request->isPost)
        {
            if (Setting::setData('special', Yii::$app->request->post('setting')))
            {
                return $this->message('修改成功', $this->redirect(['special-message']));
            }
        }

        return $this->render('special-message',[
            'list' => Setting::specialConfig(),
        ]);
    }
}

backend/modules/wechat/views/setting/history-stat.php
<?php
use yii\widgets\ActiveForm;

$this->title = '参数';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"><?= $this->title; ?></h3>
            </div>
            <?php $form = ActiveForm::begin([
                'fieldConfig' => [
                    'template' => "<div class='col-sm-2 text-right'>{label}</div><div class='col-sm-10'>{input}{hint}{error}</div>",
                ]
            ]); ?>
            <div class="box-body">
                <?= $form->field($model, 'history_status')->radioList([1 => '开启', 0 => '关闭'])->hint('开启此项后，系统将记录用户与系统的往来消息记录。') ?>
                <?= $form->field($model, 'msg_history_date')->textInput()->hint('设置保留历史消息记录的天数，为0则为保留全部，需要开启定时任务。') ?>
                <?= $form->field($model, 'utilization_status')->radioList([1 => '开启', 0 => '关闭'])->hint('开启此项后，系统将记录系统中的规则的使用情况，并生成走势图。') ?>
            </div>
            <div class="box-footer text-center">
                <button class="btn btn-primary" type="submit">保存</button>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/modules/wechat/views/setting/special-message.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = '非文字回复 ';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li><a href="<?= Url::to(['rule/index']); ?>"> 关键字自动回复</a></li>
                <li class="active"><a href="<?= Url::to(['setting/special-message']); ?>"> 非文字自动回复</a></li>
                <li><a href="<?= Url::to(['reply-default/index']); ?>"> 关注/默认回复</a></li>
            </ul>
            <div class="tab-content">
                <div class="active tab-pane rf-auto">
                    <?php $form = ActiveForm::begin(); ?>
                    <div class="col-sm-12">
                        <?php foreach ($list as $key => $row){ ?>
                            <div class="form-group">
                                <label class="control-label"><?= $row['title'] ?></label>
                                <div>
                                    <label><input name="setting[<?= $key ?>][type]" value="1" type="radio" <?= $row['type'] == 1 ? 'checked' : '' ?> onclick="$(this).parent().parent().next().show();$(this).parent().parent().next().next().hide();"> 关键字</label>
                                    <label><input name="setting[<?= $key ?>][type]" value="2" type="radio" <?= $row['type'] == 1 ? '' : 'checked' ?> onclick="$(this).parent().parent().next().hide();$(this).parent().parent().next().next().show();"> 模块</label>
                                </div>
                                <div style="display: <?= $row['type'] == 1 ? 'block' : 'none' ?>">
                                    <input class="form-control" name="setting[<?= $key ?>][content]" value="<?= $row['content'] ?>" type="text">
                                </div>
                                <div style="display: <?= $row['type'] == 1 ? "none" : "block" ?>">
                                    <select name="setting[<?= $key ?>][selected]" class="form-control">
                                        <option value="" selected>不处理(使用系统默认回复)</option>
                                        <!--<option value="custom">多客服转接</option>-->
                                        <?php foreach ($row['module'] as $k => $item){ ?>
                                            <option value="<?= $k ?>" <?php if(isset($row['selected']) && $k == $row['selected']){?>selected<?php } ?>><?= $item ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="hint-block">如果【<?= $row['title'] ?>】到达时, 将会采用选中的模块来处理. 如果选择"不处理", 那么这个消息将会使用系统默认回复来回复</div>
                                <div class="help-block"></div>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="col-sm-12 text-center">
                        <button class="btn btn-primary" type="submit">保存</button>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>